# Generated by Django 5.1.5 on 2025-02-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='cb5e5aad', editable=False, max_length=100, unique=True),
        ),
    ]
