# Generated by Django 5.1.5 on 2025-01-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='85b1ec5b', editable=False, max_length=100, unique=True),
        ),
    ]
