# Generated by Django 5.1.5 on 2025-02-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_id'),
    ]

    operations = [
    ]
