# Generated by Django 5.1.5 on 2025-02-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250206_1658'),
    ]

    operations = [
    ]
