# Generated by Django 5.1.5 on 2025-02-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250206_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='7951df0b', editable=False, max_length=100, unique=True),
        ),
    ]
