# Generated by Django 5.1.5 on 2025-02-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_id'),
    ]

    operations = [
    ]
