# Generated by Django 4.2.19 on 2025-02-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='860e836e', editable=False, max_length=100, unique=True),
        ),
    ]
