# Generated by Django 5.1.5 on 2025-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='e1102d3d', editable=False, max_length=100, unique=True),
        ),
    ]
