# Generated by Django 5.1.5 on 2025-02-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='9fc3858a', editable=False, max_length=100, unique=True),
        ),
    ]
