# Generated by Django 5.1.5 on 2025-02-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(blank=True, default='https://yourdomain.com/static/default_profile.png', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='98f87684', editable=False, max_length=100, unique=True),
        ),
    ]
