# Generated by Django 5.1.5 on 2025-02-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='e4e2d630', editable=False, max_length=100, unique=True),
        ),
    ]
