# Generated by Django 5.1.5 on 2025-02-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_profile_image_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(blank=True, default='/static/defaultimage/default-image.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='7c808f47', editable=False, max_length=100, unique=True),
        ),
    ]
