# Generated by Django 5.1.5 on 2025-02-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_user_id'),
        ('users', '0013_alter_customuser_profile_image_and_more'),
    ]

    operations = [
    ]
