# Generated by Django 5.1.5 on 2025-02-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20250206_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='bf515471', editable=False, max_length=100, unique=True),
        ),
    ]
