# Generated by Django 5.1.5 on 2025-02-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='9d1c7996', editable=False, max_length=100, unique=True),
        ),
    ]
