# Generated by Django 5.1.5 on 2025-02-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.ManyToManyField(blank=True, through='course.CourseKeyword', to='course.keyword'),
        ),
    ]
