# Generated by Django 5.1.5 on 2025-01-30 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.PositiveIntegerField()),
                ('pace', models.DecimalField(decimal_places=2, max_digits=4)),
                ('calories', models.PositiveIntegerField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('path', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_time', models.PositiveIntegerField()),
                ('avg_pace', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_calories', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
