# Generated by Django 5.1.5 on 2025-02-06 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.CharField(default='00:00:00', max_length=15)),
                ('pace', models.DecimalField(decimal_places=2, max_digits=4)),
                ('calories', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='record_images/%Y%m%d')),
                ('memo', models.TextField(blank=True, null=True)),
                ('path', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_time', models.PositiveIntegerField(default=0)),
                ('avg_pace', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
