# Generated by Django 5.1.5 on 2025-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
