# Generated by Django 5.1.5 on 2025-01-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_detail_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='created_at',
            field=models.DateField(),
        ),
    ]
