# Generated by Django 5.1.5 on 2025-01-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_detail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
