# Generated by Django 5.1.5 on 2025-02-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_detail_end_time_detail_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='record_image/%Y%m%d'),
        ),
    ]
