# Generated by Django 5.1.5 on 2025-02-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='record_images/%Y%m%d'),
        ),
    ]
