# Generated by Django 5.1.5 on 2025-02-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_alter_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='avg_pace',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
